#
# Labtainer Dockerfile for dc-ac-combined-extract
#
ARG registry
FROM $registry/labtainer.base2

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version base="labtainers/labtainer.base2.739eee77f8d3"

ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
        libglib2.0-0 \
        libgl1 \
        python3 \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*

ADD $labdir/sys_$lab.tar.gz /

RUN id -u $user_name >/dev/null 2>&1 || useradd -ms /bin/bash $user_name \
    && echo "$user_name:$password" | chpasswd \
    && adduser $user_name sudo

RUN install -d -m 0755 -o $user_name -g $user_name \
        /home/$user_name/.local \
        /home/$user_name/.local/bin \
        /home/$user_name/.local/result

USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$lab.tar.gz $HOME

USER root
RUN install -d -m 0755 -o $user_name -g $user_name \
        /home/$user_name/.local \
        /home/$user_name/.local/bin \
        /home/$user_name/.local/result \
    && chown -R $user_name:$user_name /home/$user_name

RUN python3 -m pip install --no-cache-dir \
        numpy \
        opencv-python-headless \
        pytest \
    && chown -R $user_name:$user_name /home/$user_name

CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]
