#
# Labtainer Dockerfile for dc-ac-combined-extract
#
ARG registry
FROM $registry/labtainer.base

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG apt_source

ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
        libglib2.0-0 \
        libgl1 \
        python3 \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*

ADD $labdir/sys_$lab.tar.gz /

RUN useradd -ms /bin/bash $user_name \
    && echo "$user_name:$user_name" | chpasswd \
    && adduser $user_name sudo

USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$lab.tar.gz $HOME

USER root
RUN python3 -m pip install --break-system-packages --no-cache-dir \
        numpy \
        opencv-python-headless \
        pytest \
    && chown -R $user_name:$user_name /home/$user_name

CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]
